<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-04T16:17:59 IST" name="All Test Suite" finished-at="2024-03-04T16:17:59 IST" duration-ms="329">
    <groups>
    </groups>
    <test started-at="2024-03-04T16:17:59 IST" name="C:/Users/hp/IdeaProjects/Maven_project" finished-at="2024-03-04T16:17:59 IST" duration-ms="329">
      <class name="testng.FailedTestCases">
        <test-method signature="testCase1()[pri:0, instance:testng.FailedTestCases@68267da0]" started-at="2024-03-04T16:17:59 IST" name="testCase1" finished-at="2024-03-04T16:17:59 IST" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method signature="testCase2()[pri:0, instance:testng.FailedTestCases@68267da0]" started-at="2024-03-04T16:17:59 IST" name="testCase2" finished-at="2024-03-04T16:17:59 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method signature="verifyFundTransfer()[pri:0, instance:testng.FailedTestCases@68267da0]" started-at="2024-03-04T16:17:59 IST" name="verifyFundTransfer" finished-at="2024-03-04T16:17:59 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFundTransfer -->
        <test-method signature="verifyHomepage()[pri:0, instance:testng.FailedTestCases@68267da0]" started-at="2024-03-04T16:17:59 IST" name="verifyHomepage" finished-at="2024-03-04T16:17:59 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomepage -->
        <test-method signature="verifyLogin()[pri:0, instance:testng.FailedTestCases@68267da0]" started-at="2024-03-04T16:17:59 IST" name="verifyLogin" finished-at="2024-03-04T16:17:59 IST" duration-ms="76" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testng.FailedTestCases.verifyLogin(FailedTestCases.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- testng.FailedTestCases -->
    </test> <!-- C:/Users/hp/IdeaProjects/Maven_project -->
  </suite> <!-- All Test Suite -->
</testng-results>
